name: Build & Release on PR Merge

on:
  pull_request:
    types:
      - closed
    branches: 
      - main
  workflow_dispatch:
    

jobs:
  draft_release:
    permissions:
      contents: write
    name: Create Draft Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      release_version: ${{ steps.tag.outputs.new_tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      semver_commit_hash: ${{ steps.semver_commit.outputs.commit_hash }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: Bump version and push tag
      id: tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Bump package.json version
      id: npm-version
      uses: reedyuk/npm-version@1.2.1
      with:
        version: ${{ steps.tag.outputs.new_version }}

    - name: Commit semver changes to repo
      id: semver_commit
      uses: stefanzweifel/git-auto-commit-action@v4.16.0
      with:
        branch: main


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        release_name: ${{ steps.tag.outputs.new_tag }}
        body: ${{ steps.tag.outputs.changelog }}
        draft: true
        prerelease: false

  build:
    needs: [draft_release]
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.draft_release.outputs.semver_commit_hash }}
      
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Log the build output
        run: ls build -R

      - name: Put build into ZIP
        run: (cd build && zip -r - .) >Sourcepool-Client-Web-${{ needs.draft_release.outputs.release_version }}.zip



      - name: Upload Build to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Sourcepool-Client-Web-${{ needs.draft_release.outputs.release_version }}.zip
          tag_name: ${{ needs.draft_release.outputs.release_version }}
          draft: true
  

  make_release:
    needs: [draft_release, build]
    name: Publish the Draft Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Mark release as published
      uses: eregon/publish-release@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ needs.draft_release.outputs.release_id }}
